Repository deforum-art/deforum-for-automatic1111-webui, pull requests merged in 2022-12, with the labels that each got.

#122 add checksum for downloaded models
  scripts/deforum_helpers/depth.py
Labels: enhancement, 3D

#155 fix resume issue w/ depth maps saved in output dir
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/settings.py
Labels: bug, 3D, fix inside

#156 Always load the midas model on predict_depths
  scripts/deforum_helpers/render.py
Labels: bug, 3D, fix inside

#159 QoL-only features from #74: blank frames reroll, anti-blur
  scripts/deforum.py
  scripts/deforum_helpers/animation.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/generate.py
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/settings.py
Labels: enhancement
