Repository deforum-art/deforum-for-automatic1111-webui, pull requests merged in 2023-01, with the labels that each got.

#198 Hybrid Video Compositing
  requirements.txt
  scripts/deforum.py
  scripts/deforum_helpers/animation_key_frames.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/hybrid_video.py
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/seed.py
  scripts/deforum_helpers/settings.py
Labels: enhancement, video input

#191 Option to store frames in RAM instead of disc
  scripts/deforum.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/render_modes.py
  scripts/deforum_helpers/save_images.py
  scripts/deforum_helpers/settings.py
Labels: enhancement, output

#241 feature: add checkpoint schedule
  scripts/deforum.py
  scripts/deforum_helpers/animation_key_frames.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/generate.py
  scripts/deforum_helpers/render.py
Labels: enhancement

#257 Reduce args insertion to only one place
  scripts/deforum.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/settings.py
Labels: code quality

#247 Frame insertion and animation looping
  javascript/deforum-hints.js
  scripts/deforum.py
  scripts/deforum_helpers/animation_key_frames.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/generate.py
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/render_modes.py
  scripts/deforum_helpers/settings.py
Labels: enhancement

#261 Reduce torch<->(cv2 and pil) conversions
  scripts/deforum.py
  scripts/deforum_helpers/animation.py
  scripts/deforum_helpers/blank_frame_reroll.py
  scripts/deforum_helpers/generate.py
  scripts/deforum_helpers/image_sharpening.py
  scripts/deforum_helpers/noise.py
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/render_modes.py
  scripts/deforum_helpers/settings.py
  scripts/deforum_helpers/word_masking.py
Labels: enhancement, 3D, 2D, output, code quality

#260 Better UI and cleanups v01
  javascript/deforum-hints.js
  scripts/deforum.py
  scripts/deforum_helpers/args.py
  scripts/deforum_helpers/generate.py
  scripts/deforum_helpers/load_images.py
  scripts/deforum_helpers/render.py
  scripts/deforum_helpers/src/rife/inference_video.py
  scripts/deforum_helpers/webui_sd_pipeline.py
Labels: enhancement, UI
